add unit-test.

diff --git a/.github/workflows/unit-tests.yml b/.github/workflows/unit-tests.yml
--- a/.github/workflows/unit-tests.yml
+++ b/.github/workflows/unit-tests.yml
@@ -184,3 +184,13 @@ jobs:
           else
             echo "Caltech101 dataset failed to download. Skipping SR example test."
           fi
+      - name: Run CIFAR10 with Ray Tune and Ignite
+        if: ${{ matrix.os == 'ubuntu-latest' }}
+        run: |
+          set -e
+          echo "Testing the CIFAR10 with Ray Tune and Ignite example..."
+          if python -c "import torchvision; import torch; import ray; import ignite;"; then
+            python examples/cifar10_raytune/main.py --num_epochs 1 --num_samples 1 --cpus_per_trial 1 --gpus_per_trial 0 --data_dir ./data
+          else
+            echo "CIFAR10 with Ray Tune and Ignite example failed to download. Skipping Ray Tune and Ignite example test."
+          fi
